import fs from 'node:fs';
import path from 'node:path';

export const GENERATOR_SIGNATURE = 'Generated by ai-project-structure-template';
export const GENERATOR_HEADER = `<!-- ${GENERATOR_SIGNATURE}. Do not edit directly. Edit canonical .agents/ sources, then run 'node bin/create-preset.mjs sync'. -->`;

export function isManagedFile(filePath) {
  if (!fs.existsSync(filePath)) return false;
  try {
    const head = fs.readFileSync(filePath, 'utf8').slice(0, 500);
    return (
      head.includes(GENERATOR_SIGNATURE) ||
      head.includes('Generated from .agents/') ||
      head.includes('Generated from canonical') ||
      head.includes('Generated adapter summary')
    );
  } catch {
    return false;
  }
}

export function writeFileSafe(targetPath, content, options = {}) {
  const { dryRun = false, force = false } = options;
  const dir = path.dirname(targetPath);

  if (fs.existsSync(targetPath)) {
    const existing = fs.readFileSync(targetPath, 'utf8');
    if (existing === content) {
      return { status: 'unchanged', path: targetPath };
    }
    // If not managed and force not set, avoid clobbering user file
    if (!force && !isManagedFile(targetPath)) {
      return { status: 'skipped_user_file', path: targetPath };
    }
    if (!dryRun) {
      fs.writeFileSync(targetPath, content, 'utf8');
    }
    return { status: 'updated', path: targetPath };
  }

  if (!dryRun) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(targetPath, content, 'utf8');
  }
  return { status: 'created', path: targetPath };
}

export function copyDirectorySafe(srcDir, destDir, options = {}) {
  const { dryRun = false } = options;
  const results = [];

  if (!fs.existsSync(srcDir)) return results;

  function copyRecursive(currentSrc, currentDest) {
    if (!fs.existsSync(currentDest) && !dryRun) {
      fs.mkdirSync(currentDest, { recursive: true });
    }
    const entries = fs.readdirSync(currentSrc, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = path.join(currentSrc, entry.name);
      const destPath = path.join(currentDest, entry.name);

      if (entry.isDirectory()) {
        copyRecursive(srcPath, destPath);
      } else if (entry.isFile()) {
        const content = fs.readFileSync(srcPath);
        if (fs.existsSync(destPath)) {
          const existing = fs.readFileSync(destPath);
          if (Buffer.compare(existing, content) === 0) {
            results.push({ status: 'unchanged', path: destPath });
            continue;
          }
        }
        if (!dryRun) {
          const parent = path.dirname(destPath);
          if (!fs.existsSync(parent)) {
            fs.mkdirSync(parent, { recursive: true });
          }
          fs.writeFileSync(destPath, content);
        }
        results.push({ status: 'copied', path: destPath });
      }
    }
  }

  copyRecursive(srcDir, destDir);
  return results;
}

export function safeMergeJson(targetPath, newJsonConfig, options = {}) {
  const { dryRun = false } = options;
  let current = {};

  if (fs.existsSync(targetPath)) {
    try {
      current = JSON.parse(fs.readFileSync(targetPath, 'utf8'));
    } catch {
      current = {};
    }
  }

  const merged = { ...current };

  for (const [key, value] of Object.entries(newJsonConfig)) {
    if (Array.isArray(value)) {
      const existingArray = Array.isArray(merged[key]) ? merged[key] : [];
      const combined = [...existingArray];
      for (const item of value) {
        if (!combined.includes(item)) {
          combined.push(item);
        }
      }
      merged[key] = combined;
    } else if (value && typeof value === 'object') {
      merged[key] = { ...(merged[key] || {}), ...value };
    } else {
      merged[key] = value;
    }
  }

  const output = JSON.stringify(merged, null, 2) + '\n';
  return writeFileSafe(targetPath, output, { dryRun, force: true });
}
